app:
    resource: "@AppBundle/Controller/"
    type:     annotation
main:
    path:     /
    defaults: { _controller: AppBundle:main }
evaluation_create:
    path:     /evaluation/mock
    defaults: { _controller: AppBundle:Evaluation:mockEvaluation }
